### PR TITLE
v1.1.3

### PR DESCRIPTION
**Pull request by kimhongzhang323**

### CODE REVIEW

**Review by YangYiYap — APPROVED** [review]
gooood

**Review by jelwingeuan — CHANGES_REQUESTED** [review]
update database:)

**Comment by kimhongzhang323** [comment]
1. Dont look into admin
2. Appointment Page updated
3. Need fix on app.py due to new DB 
4. About Page updated
5. Footer Bug Fixed

**Review by jelwingeuan — APPROVED** [review]

**Comment by jelwingeuan** [comment]
Merged On (2024.04.28, 13:42)

**Pull request merged**
